type Account {
  customer: Customer!
  email: String!
  id: ID!
  name: String!
  role: String!
}

type Address {
  city: String!
  country: String!
  postalCode: String!
  streetNameAndHouseNumber: String!
}

input AllowListInput {
  """
  IP address or a CIDR including the subnet
  """
  ip: String!

  """
  """
  state: State! = PRESENT
}

type AuditLog {
  account: Account
  changeSet: [AuditLogChange!]!
  eventType: String!
  id: ID!
  modelId: Int!
  modelName: String!
  occurredAt: String!
  tags: [String!]!
}

type AuditLogChange {
  name: String!
  newValue: String
  oldValue: String
}

input AuditLogFilterInput {
  eventTypes: [String!]!
  modelNames: [String!]!
}

type AutoScaling {
  replicas: AutoScalingReplicas!
  triggers: [AutoScalingTrigger!]!
}

input AutoScalingInput {
  replicas: ReplicasInput!
  triggers: [AutoScalingTriggerInput!]!
}

type AutoScalingReplicas {
  maximum: Int!
  minimum: Int!
}

type AutoScalingTrigger {
  threshold: Int!
  type: String!
}

input AutoScalingTriggerInput {
  threshold: Int!
  type: AutoScalingType!
}

enum AutoScalingType {
  CPU
  MEMORY
}

type CloudDatabase {
  connectionString: String!
  createdAt: DateTime!
  deletedAt: DateTime
  hostname: String!
  id: ID!
  location: Location!
  name: String!
  nodeType: NodeType!
  state: String!
  username: String!
  version: DatabaseVersion!
  whitelist: [String!]!
}

type CloudDatabaseAdvisory implements CloudDatabaseAdvisoryInterface {
  createdAt: String!
  identifier: String!
  message: String!
}

interface CloudDatabaseAdvisoryInterface {
  createdAt: String!
  identifier: String!
  message: String!
}

type CloudDatabaseAdvisoryMissingIndex implements CloudDatabaseAdvisoryInterface {
  createdAt: String!
  databaseName: String!
  identifier: String!
  message: String!
}

type CloudDatabaseCluster {
  adminUser: DatabaseUser
  createdAt: DateTime!
  databases: [Database!]!
  externalConnection: ExternalConnection
  hostname: String!
  id: String!
  locked: Boolean!
  name: String!
  namespace: Namespace!
  plan: Plan!
  port: Int!
  spec: Spec!
  state: String!
  users: [DatabaseUser!]!
}

type CloudDatabaseClusterAdvisor implements CloudDatabaseClusterFeature {
  enabled: Boolean!
  status: String!
}

"""
Input for create cloud database cluster.

A database cluster is accessible from within the namespace your created it in.
There is no limit on the number of users, or database.
"""
input CloudDatabaseClusterCreateInput {
  """
  """
  databases: [DatabaseInput!] = null

  """
  """
  externalConnection: ExternalConnectionInput = null

  """
  """
  name: String!

  """
  """
  namespace: String!

  """
  """
  plan: String!

  """
  """
  spec: CloudDatabaseClusterSpecInput!

  """
  """
  users: [DatabaseUserInput!] = null
}

input CloudDatabaseClusterDatabaseCreateInput {
  """
  """
  cluster: CloudDatabaseClusterResourceInput!

  """
  """
  database: DatabaseInput!
}

input CloudDatabaseClusterDatabaseResourceInput {
  """
  """
  cluster: CloudDatabaseClusterResourceInput!

  """
  """
  name: String!
}

interface CloudDatabaseClusterFeature {
  enabled: Boolean!
  status: String!
}

type CloudDatabaseClusterFeatureImpl implements CloudDatabaseClusterFeature {
  enabled: Boolean!
  status: String!
}

"""
Input for create cloud database cluster.

A database cluster is accessible from within the namespace your created it in.
There is no limit on the number of users, or database.
"""
input CloudDatabaseClusterModifyInput {
  """
  """
  databases: [DatabaseInput!]

  """
  """
  externalConnection: ExternalConnectionInput

  """
  """
  name: String!

  """
  """
  namespace: String!

  """
  """
  users: [DatabaseUserInput!]
}

input CloudDatabaseClusterResourceInput {
  """
  """
  name: String!

  """
  """
  namespace: String!
}

input CloudDatabaseClusterSpecInput {
  """
  """
  type: String!

  """
  """
  version: String!
}

input CloudDatabaseClusterUserCreateInput {
  """
  """
  cluster: CloudDatabaseClusterResourceInput!

  """
  """
  user: DatabaseUserInput!
}

input CloudDatabaseClusterUserModifyInput {
  """
  """
  cluster: CloudDatabaseClusterResourceInput

  """
  """
  user: DatabaseUserInput
}

input CloudDatabaseClusterUserResourceInput {
  """
  """
  cluster: CloudDatabaseClusterResourceInput!

  """
  """
  name: String!
}

type Container {
  autoScaling: AutoScaling
  availableReplicas: Int!
  command: [String!]
  containerType: ContainerType! @deprecated(reason: "use `type` instead")
  createdAt: DateTime!
  deletedAt: DateTime
    @deprecated(reason: "this field will be removed in the future, and doesn't have a replacement")
  entrypoint: [String!]
  environmentVariables: [EnvironmentVariable!]!
  externalConnection: ExternalConnection
  healthCheck: HealthCheck
  id: ID!
  image: String!
  ingresses: [Ingress!]!
  locked: Boolean!
  modifiedAt: DateTime
  mounts: [Mount!]!
  name: String!
  numberOfReplicas: Int!
  ports: [String!]!
  privateRegistry: PrivateRegistry
  replicas: [Replica!]!
  resourceSpecification: ResourceSpecification! @deprecated(reason: "use `resources` instead")
  resources: ContainerResources!
  startedAt: DateTime
    @deprecated(reason: "this field will be removed in the future, and doesn't have a replacement'")
  state: String!
  type: ContainerType!
}

input ContainerCreateInput {
  """
  Command to run.
  This is the command executed at the given schedule.
  When the field is omitted, the default command of the image will be used.

  Null will reset the command to the default.
  The command will be passed to the entrypoint as arguments. Use quotes to pass an argument with spaces.

  Environment variables can be used in the command by using the syntax `$(ENVIRONMENT_VARIABLE)`.

  Example: `echo "Hello $(NAME)"`.

  This field is defined in docker exec format. https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
  """
  command: [String!]

  """
  Entrypoint of the container.
  This field will overwrite the default entrypoint of the image. When the field is omitted, the default entrypoint of the image will be used.

  Null will reset the command to the default.

  Entry point is the first command executed when the container starts. It will receive the command as arguments.
  For example when the entrypoint is `python`, the command `app.py` will be executed as `python app.py`.

  This field is defined in docker exec format. https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
  """
  entrypoint: [String!]

  """
  Environment variables to be set in the job.
  """
  environmentVariables: [EnvironmentVariableInput!] = []

  """
  """
  externalConnection: ExternalConnectionInput = null

  """
  Health check performed to check the status of the container.
  Health checks are directly performed on the container so your application must expose
  the port. Port mappings specified in the ports field are not used by the health check.

  When you want to disable the health check you must send us a null value. To leave the
  current health check unchanged you can omit this field.
  """
  healthCheck: HealthCheckInput = null

  """
  """
  image: String = null

  """
  """
  ingresses: [IngressInput!] = null

  """
  """
  mounts: [MountInput!]

  """
  """
  name: String!

  """
  """
  namespace: String!

  """
  """
  ports: [String!]

  """
  """
  registry: String = null

  """
  """
  resources: ContainerResources = null

  """
  """
  scaling: ScalingInput = null

  """
  """
  type: ContainerType! = DEFAULT
}

input ContainerDeleteInput {
  """
  """
  name: String!

  """
  """
  namespace: String!
}

type ContainerEndpoint {
  allowList: [String!]!
  containerPort: Int!
  id: String!
  ipv4Address: String!
  ipv6Address: String!
  port: Int!
}

type ContainerJob {
  command: [String!]
  enabled: Boolean!
  entrypoint: [String!]
  environmentVariables: [EnvironmentVariable!]!
  image: String!
  locked: Boolean!
  mounts: [Mount!]!
  name: String!
  namespace: Namespace!
  privateRegistry: PrivateRegistry
  resources: ContainerResources!
  runs: [ContainerJobRun!]!
  schedule: String!
  state: String!
}

input ContainerJobCreateInput {
  """
  Command to run.
  This is the command executed at the given schedule.
  When the field is omitted, the default command of the image will be used.

  Null will reset the command to the default.
  The command will be passed to the entrypoint as arguments. Use quotes to pass an argument with spaces.

  Environment variables can be used in the command by using the syntax `$(ENVIRONMENT_VARIABLE)`.

  Example: `echo "Hello $(NAME)"`.

  This field is defined in docker exec format. https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
  """
  command: [String!]

  """
  Enable or disable the job.
  By disabling a job, it will not be executed, we do keep the configuration.
  """
  enabled: Boolean! = true

  """
  Entrypoint of the container.
  This field will overwrite the default entrypoint of the image. When the field is omitted, the default entrypoint of the image will be used.

  Null will reset the command to the default.

  Entry point is the first command executed when the container starts. It will receive the command as arguments.
  For example when the entrypoint is `python`, the command `app.py` will be executed as `python app.py`.

  This field is defined in docker exec format. https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
  """
  entrypoint: [String!]

  """
  Environment variables to be set in the job.
  """
  environmentVariables: [EnvironmentVariableInput!] = []

  """
  """
  image: String!

  """
  """
  mounts: [MountInput!]

  """
  """
  name: String!

  """
  """
  namespace: String!

  """
  """
  registry: String = null

  """
  """
  resources: ContainerResources!

  """
  Cron notation to schedule jobs.
  Format is equal to regular cron notation.
  For example, to run a job every day at 4am, use `0 4 * * *`.
  You can use https://crontab.guru/ to help you build your cron expressions.
  """
  schedule: String!
}

input ContainerJobModifyInput {
  """
  Command to run.
  This is the command executed at the given schedule.
  When the field is omitted, the default command of the image will be used.

  Null will reset the command to the default.
  The command will be passed to the entrypoint as arguments. Use quotes to pass an argument with spaces.

  Environment variables can be used in the command by using the syntax `$(ENVIRONMENT_VARIABLE)`.

  Example: `echo "Hello $(NAME)"`.

  This field is defined in docker exec format. https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
  """
  command: [String!]

  """
  Enable or disable the job.
  By disabling a job, it will not be executed, we do keep the configuration.
  """
  enabled: Boolean

  """
  Entrypoint of the container.
  This field will overwrite the default entrypoint of the image. When the field is omitted, the default entrypoint of the image will be used.

  Null will reset the command to the default.

  Entry point is the first command executed when the container starts. It will receive the command as arguments.
  For example when the entrypoint is `python`, the command `app.py` will be executed as `python app.py`.

  This field is defined in docker exec format. https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
  """
  entrypoint: [String!]

  """
  Environment variables to be set in the job.
  """
  environmentVariables: [EnvironmentVariableInput!]

  """
  """
  image: String

  """
  """
  mounts: [MountInput!]

  """
  """
  name: String!

  """
  """
  namespace: String!

  """
  """
  registry: String

  """
  """
  resources: ContainerResources

  """
  Cron notation to schedule jobs.
  Format is equal to regular cron notation.
  For example, to run a job every day at 4am, use `0 4 * * *`.
  You can use https://crontab.guru/ to help you build your cron expressions.
  """
  schedule: String
}

type ContainerJobPriceBreakdown implements ResourcePriceBreakdownInterface {
  name: String!
  price: Price!
  resourceType: PriceBreakdownResourceType!
  runs: [ContainerJobRunPriceBreakdown!]!
}

type ContainerJobRun {
  duration: Int
  endTime: DateTime
  message: String
  name: String!
  startTime: DateTime
  status: String!
}

type ContainerJobRunPriceBreakdown {
  cpu(unit: CpuUnit = CPU): Float!
  duration: Int!
  memory(unit: Unit = GB): Float!
  price: Price!
  runs: Int!
}

input ContainerModifyInput {
  """
  Command to run.
  This is the command executed at the given schedule.
  When the field is omitted, the default command of the image will be used.

  Null will reset the command to the default.
  The command will be passed to the entrypoint as arguments. Use quotes to pass an argument with spaces.

  Environment variables can be used in the command by using the syntax `$(ENVIRONMENT_VARIABLE)`.

  Example: `echo "Hello $(NAME)"`.

  This field is defined in docker exec format. https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
  """
  command: [String!]

  """
  Entrypoint of the container.
  This field will overwrite the default entrypoint of the image. When the field is omitted, the default entrypoint of the image will be used.

  Null will reset the command to the default.

  Entry point is the first command executed when the container starts. It will receive the command as arguments.
  For example when the entrypoint is `python`, the command `app.py` will be executed as `python app.py`.

  This field is defined in docker exec format. https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
  """
  entrypoint: [String!]

  """
  Environment variables to be set in the job.
  """
  environmentVariables: [EnvironmentVariableInput!]

  """
  """
  externalConnection: ExternalConnectionInput

  """
  Health check performed to check the status of the container.
  Health checks are directly performed on the container so your application must expose
  the port. Port mappings specified in the ports field are not used by the health check.

  When you want to disable the health check you must send us a null value. To leave the
  current health check unchanged you can omit this field.
  """
  healthCheck: HealthCheckInput

  """
  """
  image: String

  """
  """
  ingresses: [IngressInput!]

  """
  """
  mounts: [MountInput!]

  """
  """
  name: String!

  """
  """
  namespace: String!

  """
  """
  ports: [String!]

  """
  """
  registry: String

  """
  """
  resources: ContainerResources

  """
  """
  scaling: ScalingInput
}

type ContainerPriceBreakdown implements ResourcePriceBreakdownInterface {
  name: String!
  price: Price!
  replicas: [ContainerReplicaPriceBreakdown!]!
  resourceType: PriceBreakdownResourceType!
}

type ContainerReplicaPriceBreakdown {
  cpu(unit: CpuUnit = CPU): Float!
  duration: Int!
  memory(unit: Unit = GB): Float!
  name: String!
  price: Price!
}

input ContainerResourceInput {
  """
  """
  name: String!

  """
  """
  namespace: String!
}

enum ContainerResources {
  CPU_250_RAM_500
  CPU_250_RAM_1000
  CPU_250_RAM_2000
  CPU_250_RAM_3000
  CPU_250_RAM_4000
  CPU_250_RAM_5000
  CPU_250_RAM_6000
  CPU_250_RAM_7000
  CPU_250_RAM_8000
  CPU_250_RAM_9000
  CPU_250_RAM_10000
  CPU_250_RAM_11000
  CPU_250_RAM_12000
  CPU_250_RAM_13000
  CPU_250_RAM_14000
  CPU_250_RAM_15000
  CPU_250_RAM_16000
  CPU_500_RAM_500
  CPU_500_RAM_1000
  CPU_500_RAM_2000
  CPU_500_RAM_3000
  CPU_500_RAM_4000
  CPU_500_RAM_5000
  CPU_500_RAM_6000
  CPU_500_RAM_7000
  CPU_500_RAM_8000
  CPU_500_RAM_9000
  CPU_500_RAM_10000
  CPU_500_RAM_11000
  CPU_500_RAM_12000
  CPU_500_RAM_13000
  CPU_500_RAM_14000
  CPU_500_RAM_15000
  CPU_500_RAM_16000
  CPU_750_RAM_500
  CPU_750_RAM_1000
  CPU_750_RAM_2000
  CPU_750_RAM_3000
  CPU_750_RAM_4000
  CPU_750_RAM_5000
  CPU_750_RAM_6000
  CPU_750_RAM_7000
  CPU_750_RAM_8000
  CPU_750_RAM_9000
  CPU_750_RAM_10000
  CPU_750_RAM_11000
  CPU_750_RAM_12000
  CPU_750_RAM_13000
  CPU_750_RAM_14000
  CPU_750_RAM_15000
  CPU_750_RAM_16000
  CPU_1000_RAM_500
  CPU_1000_RAM_1000
  CPU_1000_RAM_2000
  CPU_1000_RAM_3000
  CPU_1000_RAM_4000
  CPU_1000_RAM_5000
  CPU_1000_RAM_6000
  CPU_1000_RAM_7000
  CPU_1000_RAM_8000
  CPU_1000_RAM_9000
  CPU_1000_RAM_10000
  CPU_1000_RAM_11000
  CPU_1000_RAM_12000
  CPU_1000_RAM_13000
  CPU_1000_RAM_14000
  CPU_1000_RAM_15000
  CPU_1000_RAM_16000
  CPU_2000_RAM_500
  CPU_2000_RAM_1000
  CPU_2000_RAM_2000
  CPU_2000_RAM_3000
  CPU_2000_RAM_4000
  CPU_2000_RAM_5000
  CPU_2000_RAM_6000
  CPU_2000_RAM_7000
  CPU_2000_RAM_8000
  CPU_2000_RAM_9000
  CPU_2000_RAM_10000
  CPU_2000_RAM_11000
  CPU_2000_RAM_12000
  CPU_2000_RAM_13000
  CPU_2000_RAM_14000
  CPU_2000_RAM_15000
  CPU_2000_RAM_16000
  CPU_3000_RAM_500
  CPU_3000_RAM_1000
  CPU_3000_RAM_2000
  CPU_3000_RAM_3000
  CPU_3000_RAM_4000
  CPU_3000_RAM_5000
  CPU_3000_RAM_6000
  CPU_3000_RAM_7000
  CPU_3000_RAM_8000
  CPU_3000_RAM_9000
  CPU_3000_RAM_10000
  CPU_3000_RAM_11000
  CPU_3000_RAM_12000
  CPU_3000_RAM_13000
  CPU_3000_RAM_14000
  CPU_3000_RAM_15000
  CPU_3000_RAM_16000
  CPU_4000_RAM_500
  CPU_4000_RAM_1000
  CPU_4000_RAM_2000
  CPU_4000_RAM_3000
  CPU_4000_RAM_4000
  CPU_4000_RAM_5000
  CPU_4000_RAM_6000
  CPU_4000_RAM_7000
  CPU_4000_RAM_8000
  CPU_4000_RAM_9000
  CPU_4000_RAM_10000
  CPU_4000_RAM_11000
  CPU_4000_RAM_12000
  CPU_4000_RAM_13000
  CPU_4000_RAM_14000
  CPU_4000_RAM_15000
  CPU_4000_RAM_16000
}

enum ContainerType {
  DEFAULT
  STARTER
}

enum CpuUnit {
  CPU
  mCPU
}

type Customer {
  billingPeriod: Int! @deprecated(reason: "this field will be removed in the future")
  credit: Price!
  hasDedicatedIp: Boolean!
  hasPaymentDetails: Boolean!
  id: ID!
  name: String! @deprecated(reason: "this field will be removed in the future")

  "\nCost: complexity = 1000, multipliers = [], defaultMultiplier = null"
  priceBreakdown(endDate: DateTime = null, startDate: DateTime = null): CustomerPriceBreakdown!
  recurringPayment: Boolean! @deprecated(reason: "this field will be removed in the future")
  suspendedReason: SuspendedReason
  termOfPayment: Int! @deprecated(reason: "this field will be removed in the future")
}

type CustomerPriceBreakdown {
  endDate: DateTime!
  resourceSum(resourceType: PriceBreakdownResourceType = ALL): PriceBreakdownResourceSum!

  """
  Returns the price breakdown of resources used during the billing period.
  """
  resources(
    name: String = null
    resourceType: PriceBreakdownResourceType = ALL
  ): [UnionIpAddressPriceBreakdownNamespacePriceBreakdown!]!
  startDate: DateTime!
}

type Database {
  description: String
  name: String!
  status: String!
}

type DatabaseClusterPriceBreakdown implements ResourcePriceBreakdownInterface {
  name: String!
  price: Price!
  resourceType: PriceBreakdownResourceType!
}

input DatabaseInput {
  """
  """
  description: String = null

  """
  """
  name: String!

  """
  """
  state: State! = PRESENT
}

enum DatabasePermission {
  READ_ONLY
  READ_WRITE
}

type DatabaseUser {
  dsn: String!
  name: String!
  password: String!
  permissions: [DatabaseUserPermission!]!
  role: String!
  status: String!
}

input DatabaseUserInput {
  """
  """
  name: String!

  """
  """
  password: String = null

  """
  """
  permissions: [DatabaseUserPermissionInput!]!

  """
  """
  state: State! = PRESENT
}

type DatabaseUserPermission {
  databaseName: String!
  permission: DatabasePermission!
}

input DatabaseUserPermissionInput {
  """
  """
  databaseName: String!

  """
  """
  permission: DatabasePermission!

  """
  """
  state: State! = PRESENT
}

type DatabaseVersion {
  id: Int!
  key: String!
  name: String!
  type: String!
}

"""
The `DateTime` scalar type represents time data, represented as an ISO-8601 encoded UTC date string.
"""
scalar DateTime

input DeleteNamespaceInput {
  """
  """
  name: String!
}

input DeleteRegistryConnectionInput {
  """
  """
  name: String!

  """
  """
  namespace: String!
}

type Endpoint {
  allowList: [String!]!
  id: String!
  ipv4Address: String!
  ipv6Address: String!
  port: Int!
}

type EnvironmentVariable {
  id: ID! @deprecated(reason: "environment variables are identified by name")
  name: String!
  secret: Boolean!
  value: String
}

input EnvironmentVariableInput {
  """
  """
  name: String!

  """
  """
  secret: Boolean! = false

  """
  """
  state: State! = PRESENT

  """
  """
  value: String!
}

type Extension {
  name: String!
}

type ExternalConnection {
  ipv4: String!
  ipv6: String!
  ports: [ExternalConnectionPort!]!
  type: String!
}

input ExternalConnectionInput {
  """
  """
  ports: [ExternalConnectionPortInput!]! = []

  """
  """
  sharedIp: Boolean! = true

  """
  """
  state: State! = PRESENT
}

type ExternalConnectionPort {
  allowList: [String!]!
  externalPort: Int!
  internalPort: Int
  protocol: Protocol!
}

input ExternalConnectionPortInput {
  """
  """
  allowList: [AllowListInput!]! = []

  """
  """
  externalPort: Int = null

  """
  Internal port is only used for external connections of containers.
  For other resources, it's automatically selected

  See ports in `ContainerCreateInput` and `ContainerModifyInput`
  """
  internalPort: Int = null

  """
  Protocol is only used for external connections of containers.
  For other resources, only TCP is allowed.
  """
  protocol: Protocol! = TCP

  """
  """
  state: State! = PRESENT
}

type HealthCheck {
  path: String!
  port: Int!
}

input HealthCheckInput {
  path: String!
  port: Int!
}

type Ingress {
  allowlist: [String!]!
  domainName: String!
  enableTLS: Boolean!
  id: ID!
  namespace: Namespace!
  port: Int!
  state: String!
  url: String!
  whitelist: [String!]! @deprecated(reason: "use field `allowlist` instead")
}

input IngressInput {
  """
  """
  domainName: String = null

  """
  """
  enableTLS: Boolean! = false

  """
  """
  port: Int!

  """
  """
  state: State! = PRESENT

  """
  """
  whitelist: [String!] = []
}

type IpAddressPriceBreakdown implements ResourcePriceBreakdownInterface {
  name: String!
  price: Price!
  resourceType: PriceBreakdownResourceType!
}

type Location {
  id: Int!
  name: String!
}

input ManualScalingInput {
  """
  """
  replicas: Int!
}

type MessageQueue {
  adminUser: MessageQueueUser
  createdAt: DateTime!
  externalConnection: ExternalConnection
  id: String!
  ingress: MessageQueueIngress!
  locked: Boolean!
  name: String!
  namespace: Namespace!
  plan: MessageQueuePlan!
  spec: MessageQueueSpec!
  state: String!
}

input MessageQueueCreateInput {
  """
  """
  allowList: [AllowListInput!] = null

  """
  """
  externalConnection: ExternalConnectionInput = null

  """
  """
  name: String!

  """
  """
  namespace: String!

  """
  """
  plan: String!

  """
  """
  spec: MessageQueueSpecInput!
}

type MessageQueueIngress {
  allowList: [String!]
  domainName: String!
  id: String!
  status: Status!
  tlsEnabled: Boolean!
}

input MessageQueueModifyInput {
  """
  """
  allowList: [AllowListInput!]

  """
  """
  externalConnection: ExternalConnectionInput

  """
  """
  name: String!

  """
  """
  namespace: String!
}

type MessageQueuePlan {
  benchmark: MessageQueuePlanBenchmark
  cpu(unit: CpuUnit = CPU): Float!
  group: String!
  id: String!
  memory(unit: Unit = GB): Float!
  name: String!
  price: Price!
  replicas: Int!
  storage(unit: Unit = GB): Float!
}

type MessageQueuePlanBenchmark {
  connections: Int!
  maximumMessageRate: Int!
  minimumMessageRate: Int!
}

type MessageQueuePriceBreakdown implements ResourcePriceBreakdownInterface {
  name: String!
  price: Price!
  resourceType: PriceBreakdownResourceType!
}

input MessageQueueResourceInput {
  """
  """
  name: String!

  """
  """
  namespace: String!
}

type MessageQueueSpec {
  patchLevelVersion: String!
  type: String!
  version: String!
}

input MessageQueueSpecInput {
  """
  """
  type: String!

  """
  """
  version: String!
}

type MessageQueueUser {
  dsn: String!
  name: String!
  password: String!
  role: String!
  status: String!
}

type Mount {
  path: String!
  volume: Volume!
}

input MountInput {
  """
  Path to mount the volume in the container.
  """
  path: String!

  """
  Set the expected state of this mount.
  When the state is set to `ABSENT`, the mount will be removed, the volume will be kept.
  """
  state: State! = PRESENT

  """
  """
  volume: MountVolumeInput!
}

input MountVolumeInput {
  """
  Create the volume if it does not exist.
  """
  autoCreate: Boolean! = true

  """
  Increase the size of the volume if it already exists.
  """
  increase: Boolean! = false

  """
  Name of the volume
  """
  name: String!

  """
  Size of the volume in GB
  """
  size: Int = null
}

type Mutation {
  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  addPrivateRegistry(
    name: String!
    namespaceId: Int!
    password: String!
    source: String!
    username: String!
    verify: Boolean = true
  ): Boolean! @deprecated(reason: "use `registryConnectionCreate` mutation")

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  cloudDatabaseClusterCreate(
    cloudDatabaseClusterInput: CloudDatabaseClusterCreateInput
  ): CloudDatabaseCluster!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  cloudDatabaseClusterDatabaseCreate(
    databaseInput: CloudDatabaseClusterDatabaseCreateInput
  ): Database!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  cloudDatabaseClusterDatabaseDelete(
    databaseInput: CloudDatabaseClusterDatabaseResourceInput!
  ): Boolean!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  cloudDatabaseClusterDelete(cloudDatabase: CloudDatabaseClusterResourceInput!): Boolean!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  cloudDatabaseClusterModify(
    cloudDatabaseClusterInput: CloudDatabaseClusterModifyInput
  ): CloudDatabaseCluster!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  cloudDatabaseClusterUserCreate(userInput: CloudDatabaseClusterUserCreateInput): DatabaseUser!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  cloudDatabaseClusterUserDelete(userInput: CloudDatabaseClusterUserResourceInput!): Boolean!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  cloudDatabaseClusterUserModify(userInput: CloudDatabaseClusterUserModifyInput): DatabaseUser!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  containerCreate(containerInput: ContainerCreateInput): Container!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  containerDelete(container: ContainerDeleteInput!): Boolean!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  containerJobCreate(scheduledJob: ContainerJobCreateInput!): ContainerJob!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  containerJobDelete(scheduledJob: ResourceNameInput!): Boolean!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  containerJobModify(scheduledJob: ContainerJobModifyInput): ContainerJob!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  containerModify(containerInput: ContainerModifyInput): Container!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  createNamespace(
    customerId: Int = null
    description: String = null
    name: String!
    pricingPlanId: Int = 2
    resourceSpecificationId: Int = null
  ): Boolean! @deprecated(reason: "use `namespaceCreate` mutation")

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  createVolume(name: String!, namespaceId: Int!, size: Int!): Volume
    @deprecated(reason: "use `volumeCreate` mutation")

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  deleteNamespace(id: Int!): Boolean! @deprecated(reason: "use `namespaceDelete` mutation")

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  deletePrivateRegistry(privateRegistryId: Int!): Boolean!
    @deprecated(reason: "use `registryConnectionDelete` mutation instead")

  """
  Deletes a volume.
  Volumes can be deleted if they are not mounted to any container.

  Cost: complexity = 100, multipliers = [], defaultMultiplier = null
  """
  deleteVolume(
    namespaceId: NamespaceId!
    volumeId: Int = null
    volumeName: String = null
  ): Boolean! @deprecated(reason: "use `volumeDelete` mutation")

  """
  Increases the size of a volume.
  Volumes sizes can only be increased. Increase of volume will not be possible if the volume state is locked.
  We do increase volumes on the fly, so the volume will be increased without any downtime.

  Cost: complexity = 100, multipliers = [], defaultMultiplier = null
  """
  increaseVolume(name: String!, namespaceId: NamespaceId!, size: Int!): Volume!
    @deprecated(reason: "use `volumeIncrease` mutation")

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  messageQueueCreate(messageQueue: MessageQueueCreateInput): MessageQueue!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  messageQueueDelete(messageQueue: MessageQueueResourceInput!): Boolean!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  messageQueueModify(messageQueue: MessageQueueModifyInput): MessageQueue!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  messageQueueUserModify(userInput: CloudDatabaseClusterUserModifyInput): MessageQueueUser!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  namespaceCreate(namespaceInput: NamespaceCreateInput!): Namespace!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  namespaceDelete(namespace: DeleteNamespaceInput!): Boolean!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  registryConnectionCreate(registryInput: RegistryCreateInput!): PrivateRegistry!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  registryConnectionDelete(registryConnection: DeleteRegistryConnectionInput!): Boolean!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  volumeCreate(volumeInput: VolumeCreateInput): Volume!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  volumeDelete(volume: VolumeResourceInput!): Boolean!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  volumeIncrease(volumeInput: VolumeModifyInput): Volume!
}

type Namespace {
  cloudDatabaseClusters: [CloudDatabaseCluster!]!
  containerJobs: [ContainerJob!]!
  containers: [Container!]!
  createdAt: DateTime!
  deletedAt: DateTime
  description: String!
  id(legacy: Boolean = true): ID!
  internalName: String!
    @deprecated(reason: "this field will be removed in the future. There is no replacement")
  messageQueues: [MessageQueue!]!
  modifiedAt: DateTime
  name: String!
  pricingPlan: PricingPlan!
  privateRegistries: [PrivateRegistry!]!
  resourceSpecification: ResourceSpecification
  state: String!
  volumes: [Volume!]
}

input NamespaceCreateInput {
  """
  """
  description: String

  """
  """
  name: String!
}

"""
The unique identifier of a cluster namespace, represented as an integer.
"""
scalar NamespaceId

type NamespacePriceBreakdown implements ResourcePriceBreakdownInterface {
  name: String!
  price: Price!

  """
  Returns the sum of the price per resource type.
  """
  resourceSum(resourceType: PriceBreakdownResourceType = ALL): PriceBreakdownResourceSum!
  resourceType: PriceBreakdownResourceType!

  """
  Returns the price breakdown of resource in this namespace.
  Each resource has its own price breakdown. Depending on the resource type you can query more or less details.
  """
  resources(resourceType: PriceBreakdownResourceType!): [ResourcePriceBreakdownInterface!]!
}

type NodeType {
  description: String
  id: Int
  key: String!
  name: String!
  numberOfNodes: Int!
  price: Price!
  specifications: NodeTypeSpecification!
}

type NodeTypeSpecification {
  cpu: Int!
  ram: Int!
  storage: Int!
}

type Plan {
  cpu: Int!
  group: String!
  id: String!
  memory(unit: Unit = GB): Float!
  name: String!
  price: Price!
  replicas: Int!
  storage: Int!
}

type Price {
  amount: Int
  currency: String
}

type PriceBreakdownResourceSum {
  price: Price!
  resourceType: PriceBreakdownResourceType!
}

enum PriceBreakdownResourceType {
  ALL
  CONTAINER
  CONTAINER_JOB
  DATABASE_CLUSTER
  IPADDRESS
  MESSAGE_QUEUE
  NAMESPACE
  STARTER_CONTAINER
  VOLUME
}

type PricingPlan {
  id: ID!
  name: String!
}

type PrivateRegistry {
  createdAt: String!
  id: ID!
  locked: Boolean!
  name: String!
  namespace: Namespace!
  source: String!
  state: String!
  username: String!
}

enum Protocol {
  TCP
  UDP
}

type Query {
  """
  Returns the current user account.
  This query will return the account of the currents api user.

  Cost: complexity = 100, multipliers = [], defaultMultiplier = null
  """
  account: Account

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  auditLogs(customerId: ID!, filter: AuditLogFilterInput = null): [AuditLog]!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  cloudDatabase(id: ID!): CloudDatabase

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  cloudDatabaseCluster(cloudDatabase: CloudDatabaseClusterResourceInput!): CloudDatabaseCluster!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  cloudDatabaseClusterPlans: [Plan!]!

  "\nCost: complexity = 750, multipliers = [], defaultMultiplier = null"
  cloudDatabaseClusterUserCredentials(
    cloudDatabase: CloudDatabaseClusterResourceInput!
    username: String!
  ): DatabaseUser!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  cloudDatabaseClusterVersions: [Spec!]!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  cloudDatabaseClusters: [CloudDatabaseCluster!]!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  cloudDatabases: [CloudDatabase!]!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  container(containerResourceInput: ContainerResourceInput = null, id: ID = null): Container!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  containerJob(name: String!, namespace: String!): ContainerJob!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  customer: Customer

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  databaseVersions: [DatabaseVersion!]!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  locations: [Location!]!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  messageQueue(messageQueue: MessageQueueResourceInput!): MessageQueue!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  messageQueuePlans: [MessageQueuePlan!]!

  "\nCost: complexity = 750, multipliers = [], defaultMultiplier = null"
  messageQueueUserCredentials(
    messageQueue: MessageQueueResourceInput!
    username: String!
  ): MessageQueueUser!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  messageQueueVersions: [MessageQueueSpec!]!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  messageQueues: [MessageQueue!]!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  namespace(id: ID = null, name: String = null): Namespace!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  namespaces: [Namespace!]!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  nodeType(id: String!): NodeType!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  nodeTypes(numberOfNodes: Int = null): [NodeType!]!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  pricingPlans: [PricingPlan!]!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  privateRegistries(namespace: String = null, namespaceId: ID = null): [PrivateRegistry!]!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  resourceSpecifications(kind: String!): [ResourceSpecification!]!

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  volume(id: ID!): Volume

  "\nCost: complexity = 100, multipliers = [], defaultMultiplier = null"
  volumes(namespaceId: Int!): [Volume!]!
}

input RegistryCreateInput {
  """
  """
  name: String!

  """
  """
  namespace: String!

  """
  """
  password: String!

  """
  """
  source: String!

  """
  """
  username: String!

  """
  """
  verify: Boolean! = true
}

type Replica {
  name: String!
  status: String!
  statusMessage: String
}

input ReplicasInput {
  maximum: Int!
  minimum: Int!
}

input ResourceNameInput {
  """
  """
  name: String!

  """
  """
  namespace: String!
}

type ResourcePriceBreakdown implements ResourcePriceBreakdownInterface {
  name: String!
  price: Price!
  resourceType: PriceBreakdownResourceType!
}

interface ResourcePriceBreakdownInterface {
  name: String!
  price: Price!
  resourceType: PriceBreakdownResourceType!
}

type ResourceSpecification {
  cpu: Float!
  id: ID!
  kind: String!
  price: Price!
  ram: Float!
}

input ScalingInput {
  auto: AutoScalingInput = null
  manual: ManualScalingInput = null
}

type Spec {
  patchLevelVersion: String!
  type: String!
  version: String!
}

type StarterContainerPriceBreakdown implements ResourcePriceBreakdownInterface {
  name: String!
  price: Price!
  resourceType: PriceBreakdownResourceType!
}

enum State {
  ABSENT
  PRESENT
}

enum Status {
  CREATED
  CREATE_REQUESTED
  CREATING
  DELETE_PENDING
  DELETE_REQUESTED
  DELETING
  FAILED
  ON_HOLD
  UNPROVISIONED
  UPDATED
  UPDATING
}

type Subscription {
  """
  A placeholder query used by thecodingmachine/graphqlite when there are no declared subscriptions.
  """
  dummySubscription: String
}

enum SuspendedReason {
  ABUSIVE_BEHAVIOUR
  DEFAULT
  MALICIOUS_ACTIVITY
  PAYMENT_ISSUES
  SUPPORTING_PROHIBITED_CONTENT
}

union UnionIpAddressPriceBreakdownNamespacePriceBreakdown =
  | IpAddressPriceBreakdown
  | NamespacePriceBreakdown

enum Unit {
  GB
  MB
  TB
}

type Volume {
  containerJobs: [ContainerJob!]!
  containers: [Container!]!
  id: ID!
  locked: Boolean!
  name: String!
  namespace: Namespace!
  size(unit: Unit = GB): Float!
  state: String!
  usage(unit: Unit = GB): Float!
}

input VolumeCreateInput {
  """
  """
  name: String!

  """
  """
  namespace: String!

  """
  """
  size: Int!
}

input VolumeModifyInput {
  """
  """
  name: String!

  """
  """
  namespace: String!

  """
  """
  size: Int!
}

type VolumePriceBreakdown implements ResourcePriceBreakdownInterface {
  name: String!
  price: Price!
  resourceType: PriceBreakdownResourceType!
}

input VolumeResourceInput {
  """
  """
  name: String!

  """
  """
  namespace: String!
}
